export enum Tag {
  HTML = 'HTML',
  CSS = 'CSS',
  JS = 'JavaScript',
  React = 'React',
  JSX = 'JSX',
  Redux = 'Redux',
  MUI = 'MUI',
  APIs = 'API:s',
  MongoDB = 'MongoDB',
  Design = 'UX/UI-design',
  React_Native = 'React Native',
  Styled_Components = 'Styled Components',
  TS = 'TypeScript',
}
